# Generated by Django 4.2.7 on 2024-08-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_auth_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
