version: '3.9'
services:
  web:
    build: .
    command: ["gunicorn", "--bind", ":8000", "backend.wsgi:application"]
    volumes:
      - .:/app
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

    networks:
      - backend-network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network

  celery-worker:
    build: .
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network
      
  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 backend.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      # - web
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    networks:
      - backend-network

  

volumes:
  db_data:
  media_volume:

networks:
  backend-network:
    driver: bridge