# Generated by Django 5.1 on 2024-08-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='rental_duration',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='access_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseprogress',
            name='access_type',
            field=models.CharField(choices=[('Rental', 'rental'), ('Lifetime', 'lifetime')], default='Lifetime', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='access_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='access_type',
            field=models.CharField(choices=[('Rental', 'rental'), ('Lifetime', 'lifetime')], default='Lifetime', max_length=20),
        ),
    ]
