# Generated by Django 5.1 on 2024-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Declined', 'declined'), ('Pending', 'pending'), ('Requested', 'requested')], default='Requested', max_length=20),
        ),
    ]
