# Generated by Django 5.1 on 2024-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_block',
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
