# Generated by Django 5.1 on 2024-09-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_level_module_is_liked_module_is_watched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='skill_level',
        ),
    ]
