# Generated by Django 5.1 on 2024-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_module_is_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseprogress',
            name='liked_modules',
            field=models.ManyToManyField(blank=True, related_name='liked_video', to='course.module'),
        ),
        migrations.AlterField(
            model_name='studentcourseprogress',
            name='watched_modules',
            field=models.ManyToManyField(blank=True, related_name='watched_video', to='course.module'),
        ),
    ]
