# Generated by Django 5.1 on 2024-09-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_studentcourseprogress_liked_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Requested', 'requested'), ('Approved', 'approved')], default='Approved', max_length=20),
        ),
    ]
