# Generated by Django 5.1 on 2024-09-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_category_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
