# Generated by Django 5.1 on 2024-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_note_module_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
