# Generated by Django 5.1 on 2024-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_module_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
