# Generated by Django 5.1 on 2024-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
