# Generated by Django 5.1 on 2024-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_option_question_alter_question_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
