# Generated by Django 5.1 on 2024-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_created_at_alter_contest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=10, null=True),
        ),
    ]
