# Generated by Django 5.1 on 2024-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_max_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='difficulty_level',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
