# Generated by Django 5.1 on 2024-10-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_contest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
    ]
