# Generated by Django 5.1 on 2024-09-10 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_difficulty_level_contest_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_participants', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.participant'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='selected_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.option'),
        ),
    ]
