# Generated by Django 5.1 on 2024-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_leaderboard_contest_alter_leaderboard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
