# Generated by Django 5.1 on 2024-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_remove_contest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
