# Generated by Django 5.1 on 2024-09-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contest',
            new_name='content',
        ),
    ]
