# Generated by Django 5.1 on 2024-09-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='content',
            new_name='description',
        ),
    ]
