# Generated by Django 5.1 on 2024-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_comment_parent_alter_comment_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='discussion',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
