# Generated by Django 5.1 on 2024-08-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_instructor_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='education',
            name='instructor',
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user_profile.tutor'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user_profile.tutor'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_profile.tutor'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
