# Generated by Django 5.1 on 2024-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_experience_instructor_remove_skill_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('requested', 'requested'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
