# Generated by Django 5.1 on 2024-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_tutor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('Verified', 'verified'), ('Requested', 'requested'), ('Pending', 'pending'), ('Rejected', 'rejected')], default='Pending', max_length=10),
        ),
    ]
